# Generated by Django 5.0.7 on 2026-05-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_contactmessage_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(default="django", max_length=300),
            preserve_default=False,
        ),
    ]
